---
title: "Reproducibility Report for Postural Hand Synergies for Tool Use by Santello, Flanders and Soechting (1998, Journal of Neuroscience)"
author: "Shivani Guptasarma (shivanig@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

A study was performed by Santello *et al.* in 1998 to investigate whether grasp postures formed by human hands showed natural patterns of coordination between the joints. Participants were asked to grasp imaginary objects of diverse shapes with their right hand. The angles between various segments of the hand were measured with a tracking glove and a principal component analysis performed on the results, revealing two major ``postural synergies". This report documents a replication of the 1998 study, using  visual tracking of the hand with a wearable headset. 

[No abstract is needed.]  Each reproducibility project will have a straightforward, no frills report of the study and reproducibility results. These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of your attempt to reproduce the results. Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for your reproducibility attempt, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  

The key analysis of interest is a **principal component analysis** of the joint angles data from grasping of a number of objects. A key finding of the original paper was that the first two principal components account for more than 80% of the variance in posture.

### Justification for choice of study

While a goal of the original experiment was to better understand the neuromuscular basis of movement, its results have proved significant for the planning of feasible grasps in robotic manipulators, as well as for the design and control of prosthetic hands. This replication was motivated by an interest in both, understanding the neural control of movement, and simplifying the control of prosthetic devices. 

### Anticipated challenges

It was anticipated that the use of visual tracking might lead to challenges with recording grasps in which some fingers were partially or completely occluded from the camera. Since the stimuli were entirely verbal, it was also expected that different subjects would interpret them differently based on their own imagined shape and size of each object. Owing to a lack of experience with implementation, some challenges were expected in obtaining joint angle data in a usable form from a proprietary headset, and setting up a pipeline with two clickers to mark the start and end of the reach-and-grasp motion.

### Links

Project repository (on Github): 

Original paper (as hosted in your repo): 

## Methods

### Description of the steps required to reproduce the results

Please describe all the steps necessary to reproduce the key result(s) of this study. 

### Differences from original study

Explicitly describe known differences in the analysis pipeline between the original paper and yours (e.g., computing environment). The goal, of course, is to minimize those differences, but differences may occur. Also, note whether such differences are anticipated to influence your ability to reproduce the original results.

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.


### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).


## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
